# Generated by Django 3.2.4 on 2021-06-04 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('university', models.CharField(max_length=100)),
                ('degree', models.CharField(max_length=20)),
                ('specialization', models.CharField(max_length=50)),
                ('grade', models.CharField(max_length=30)),
                ('location', models.CharField(max_length=100)),
                ('additional_desc', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=75)),
                ('company', models.CharField(max_length=75)),
                ('location', models.CharField(max_length=50)),
                ('startDate', models.DateField()),
                ('endDate', models.DateField(blank=True, null=True)),
                ('description', models.TextField()),
            ],
        ),
    ]
