# Generated by Django 3.2.4 on 2021-06-19 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='passingYear',
            field=models.DateField(blank=True, null=True),
        ),
    ]
