# Generated by Django 3.2.4 on 2021-06-19 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0002_education_passingyear'),
    ]

    operations = [
        migrations.CreateModel(
            name='publication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('journalName', models.CharField(max_length=100)),
                ('DOI', models.CharField(max_length=100)),
                ('link', models.CharField(max_length=150)),
                ('indexing', models.CharField(max_length=50, null=True)),
            ],
        ),
    ]
