# Generated by Django 3.2.4 on 2021-06-19 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0003_publication'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='dateOfPub',
            field=models.DateField(null=True),
        ),
    ]
