# Generated by Django 3.2.4 on 2021-06-19 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0004_publication_dateofpub'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='ISSN',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='publication',
            name='beginPage',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='publication',
            name='endPage',
            field=models.IntegerField(default=0),
        ),
    ]
