# Generated by Django 3.2.4 on 2021-06-22 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0005_auto_20210619_1804'),
    ]

    operations = [
        migrations.CreateModel(
            name='extracurricular',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('org', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=75)),
                ('startDate', models.DateField()),
                ('endDate', models.DateField(blank=True, null=True)),
                ('description', models.TextField()),
            ],
        ),
    ]
